### ISSUE TITLE
nashdev needs a logo

### ISSUE THREAD

**Issue by robotsnowfall** [nashdev/nashdev#2]
Logos lend legitimacy to even the most flippant of repos.

**Comment by robotsnowfall** [comment]
Bonus points if the logo is both good and does not feature the AT&T building or a guitar.

**Comment by egdelwonk** [comment]
![nashdevlogo](https://cloud.githubusercontent.com/assets/512548/10919842/957aa180-8232-11e5-96d8-99782d5aedeb.png)

**Comment by egdelwonk** [comment]
lol

**Comment by robotsnowfall** [comment]
works for me :+1: Anyone else?

**Comment by egdelwonk** [comment]
![nashelixir](https://cloud.githubusercontent.com/assets/512548/10919449/8b9646da-8230-11e5-94d5-0051867416b1.png)

**Comment by robotsnowfall** [comment]
@egdelwonk can you submit this as a PR that adds the logo to the Readme?

**Comment by egdelwonk** [comment]
sure
